### PR TITLE
Fix StreamContextInfo to be Send

### LINKED ISSUE #324: Soundness Bug - StreamContextInfo is not safe to send across threads
We found another soundness issue. In src/fsevent.rs we have this definition:

```
struct StreamContextInfo {
    event_fn: Arc<dyn EventFn>,
    recursive_info: HashMap<PathBuf, bool>,
}
```

This type is passed across a thread that actually listens to file changes. Unfortunately this type isn't actually send because while `pub trait EventFn: 'static + Fn(Result<Event>) + Send {}` implements `Send`, `Arc<dyn EventFn>` is not `Send`. That also requires `EventFn` to also implement `Sync`. Unfortunately just adding `Sync` doesn't compile because of some other conflicts.

### PR DESCRIPTION
**Pull request by erickt**
In #324, we found that we were passing StreamContextInfo to another thread, even though the type is not actually Send. This makes sure that StreamContextInfo is actually Send by wrapping it in a mutex.

Fixes #324

### CODE REVIEW

File: src/fsevent.rs [hunk 1]
```diff
@@ -531,14 +534,14 @@ unsafe fn callback_impl(
         for ev in translate_flags(flag, true).into_iter() {
             // TODO: precise
             let ev = ev.add_path(path.clone());
-            (*event_fn)(Ok(ev));
+            (event_fn.lock().unwrap())(Ok(ev));
```
Comment (0xpr03) [inline src/fsevent.rs:537]: I'd use an expect with a declaration what failed.

**Review by 0xpr03 — CHANGES_REQUESTED** [review]

File: src/fsevent.rs (hunk 1 above)
Comment (erickt) [reply src/fsevent.rs]: Switched to `expect()`

Comment (0xpr03) [reply src/fsevent.rs]: thanks, I meant more something about event_fn having this poisoning, but maybe that's not good

**Review by 0xpr03 — APPROVED** [review]
