### PR TITLE
fix: INotifyWatcher may raise events with no paths

### LINKED ISSUE #678: notify-debouncer-full panic on Linux with inotify
If no paths are included on an `Event`, `notify-debouncer-full` panics due to this line.  https://github.com/notify-rs/notify/blob/main/notify-debouncer-full/src/lib.rs#L274

It appear that `INotifyWatcher` on Linux sometimes includes events with no paths.

This is rare, but I'm seeing it happen in telemetry 50 times a day.

I could take a crack at addressing this issue, but I'm not sure whether the fix would be to:

- Suppress all events from `INotifyWatcher` that do not include paths. OR
- Make `notify-debouncer-full` handle events safely that don't include paths.

### PR DESCRIPTION
**Pull request by riberk**
INotifyWatcher hold inotify watch descriptors map `wd -> path` and after an `unwatch` call  the descriptor is deleted from the map. In some cases, if a lot of events are raised, it may cause race condition when the descriptor has been deleted, but event with this descriptor has already been queued. In that case INotifyWatcher doesn't know the path and just ignore the event

fixes #678

### CODE REVIEW

File: notify/src/inotify.rs [hunk 1]
```diff
@@ -618,86 +611,155 @@ impl Drop for INotifyWatcher {
...
+    /// Runs manually.
+    ///
+    /// * Save actual value of the limit: `MAX_USER_WATCHES=$(sysctl -n fs.inotify.max_user_watches)`
+    /// * Run the test.
+    /// * Set the limit to 0: `sudo sysctl fs.inotify.max_user_watches=0` while test is running
+    /// * Wait for the test to complete
+    /// * Restore the limit `sudo sysctl fs.inotify.max_user_watches=$MAX_USER_WATCHES`
+    #[test]
+    #[ignore = "requires changing sysctl fs.inotify.max_user_watches while test is running"]
+    fn recurcive_watch_calls_handler_if_creating_a_file_raises_max_files_watch() {
```
Comment (dfaust) [inline notify/src/inotify.rs:656]:
```suggestion
    fn recursive_watch_calls_handler_if_creating_a_file_raises_max_files_watch() {
```

**Comment by dfaust** [comment]
Fantastic. Thanks again!

**Comment by dfaust** [comment]
@riberk I think this would be a good time to make a new release - unless you are working on something else.

**Comment by riberk** [comment]
@dfaust it'd be good, but I don't know how I can help

**Comment by dfaust** [comment]
I will make the release. Just wanted to make sure I don't release while you are still working on something.

I'll wait with the release until my latest MR is merged as well, though.

**Comment by riberk** [comment]
Ah, now I see it. Right now I'm not working on anything
