### PR TITLE
Fixed the Event of watch dir Deletion

### LINKED ISSUE #493: Delete a directory which is watched returns Event { kind: Remove(File) }
#### System details

- OS/Platform name and version: `Fedora 38 `
- Rust version (if building from source): `rustc 1.70.0 (90c541806 2023-05-31)`
- Notify version (or commit hash if building from git): `6.0.0`
- On Linux: Kernel version: `6.3.6-200.fc38.x86_64`

#### What you did (as detailed as you can)
1. call `watcher.watch(path, non_recursive)` on a directory
2. `rm -r path`

#### What you expected
Receive `Event { kind: Remove(Folder) }`

#### What happened
Receive `Event { kind: Remove(File) }`

### PR DESCRIPTION
**Pull request by zeroishero**
Resolves #493
Deleting watched dir only returns Delete self and Ignore event. Unlike deleting other folders, it doesn't return events to check whether it is dir or not. 

I stored whether path is dir or not in watches. Taking metadata after delete event triggers is not possible.

### CODE REVIEW

File: notify/src/inotify.rs [hunk 1]
```diff
@@ -35,7 +37,7 @@ struct EventLoop {
     event_loop_rx: Receiver<EventLoopMsg>,
     inotify: Option<Inotify>,
     event_handler: Box<dyn EventHandler>,
-    watches: HashMap<PathBuf, (WatchDescriptor, WatchMask, bool)>,
+    watches: HashMap<PathBuf, (WatchDescriptor, WatchMask, bool, bool)>,
```
Comment (0xpr03) [inline notify/src/inotify.rs:40]:
```suggestion
    /// - watches HashMap Value tuple (WatchDescriptor, WatchMask, is_recursive, is_dir)
    watches: HashMap<PathBuf, (WatchDescriptor, WatchMask, bool, bool)>,
```

File: notify/src/inotify.rs [hunk 2]
```diff
@@ -296,6 +296,28 @@ impl EventLoop {
                                 );
                                 remove_watch_by_event(&path, &self.watches, &mut remove_watches);
                             }
+                            if event.mask.contains(EventMask::DELETE_SELF) {
+                                evs.push(
+                                    Event::new(EventKind::Remove(match path.clone() {
```
Comment (0xpr03) [inline notify/src/inotify.rs:301]: Can you refactor this so there is no hidden match in the value creation ? Not sure but rustfmt might also move this around a fair bit..

File: notify/src/inotify.rs [hunk 3]
```diff
@@ -296,6 +296,28 @@ impl EventLoop {
...
+                                        Some(path) => {
+                                            let current_watch = self.watches.get(&path);
+                                            match current_watch {
+                                                Some(&(_, _, _, is_dir)) => {
+                                                    if is_dir {
```
Comment (0xpr03) [inline notify/src/inotify.rs:306]: this could also be collapsed into a single match over the cases Some(..,true,), Some(..,false), None

**Review by 0xpr03 — CHANGES_REQUESTED** [review]
Thanks! I've added some comments, let me know if you want to leave them to me or refactor those parts by yourself.

File: notify/src/inotify.rs (hunk 3 above)
Comment (zeroishero) [reply notify/src/inotify.rs:306]: Done

File: notify/src/inotify.rs (hunk 2 above)
Comment (zeroishero) [reply notify/src/inotify.rs:301]: I took the logic to check for Dir Type outside push method.

**Comment by zeroishero** [comment]
I added the comment for watches HashMap.

File: notify/src/inotify.rs (hunk 1 above)
Comment (zeroishero) [reply notify/src/inotify.rs:40]: done

Comment (0xpr03) [reply notify/src/inotify.rs:40]: can this be a doc comment ? `///`

Comment (0xpr03) [reply notify/src/inotify.rs:41]: thanks, but please also remove the upper one :)

**Comment by zeroishero** [comment]
@0xpr03 is there anything I should add?

**Comment by 0xpr03** [comment]
Any reason to close it ? I did ask for another thing: The unwrap you're using seems like something that could crash. Otherwise the PR is fine.

**Comment by zeroishero** [comment]
Oh.. I thought that didn't passed review and closed it. I didn't see the new change. I will check the unwrap one.

**Comment by zeroishero** [comment]
@0xpr03 I used unwrap because the if clause checks for is_none().  Can it crash?

anyway, I refactored it to not use unwrap.

File: notify/src/inotify.rs (hunk 1 above)
Comment (zeroishero) [reply notify/src/inotify.rs:41]: Done. I thought you meant the comment above.

**Comment by zeroishero** [comment]
@0xpr03 are there more changes I should do before it gets approved?

**Comment by 0xpr03** [comment]
Looks good, I'm just too busy right now and don't wanna rush things.

**Review by 0xpr03 — APPROVED** [review]

**Comment by 0xpr03** [comment]
Huh so apparently github never send my review.. Sorry for that..

File: notify/src/inotify.rs [hunk 4]
```diff
@@ -296,6 +297,26 @@ impl EventLoop {
                                 );
                                 remove_watch_by_event(&path, &self.watches, &mut remove_watches);
                             }
+                            if event.mask.contains(EventMask::DELETE_SELF) {
+                                let remove_kind: RemoveKind;
+
+                                if path.is_none() {
+                                    remove_kind = RemoveKind::Other
+                                } else {
+                                    let watched_path = path.clone().unwrap();
```
[the remark this answers is not in the document]
Comment (hexofyore) [reply notify/src/inotify.rs]: considering it's in else branch which checks for is_none condition, it shouldn't fail on unwrap. 
The clone is there coz it needs to be owned by Event but path is in notify.

[the remark this answers is not in the document]
Comment (zeroishero) [reply notify/src/inotify.rs]: considering it's in else branch which checks for is_none condition, it shouldn't fail on unwrap.
The clone is there coz it needs to be owned by Event but path is in notify.
