### PR TITLE
Fix/suppress warnings

### LINKED ISSUE #251: Future rustc compatibility lint WHERE_CLAUSES_OBJECT_SAFETY
rustc 1.42.0 (up to 1.44.1) report warnings during compilation of 5.0.0-pre.3

```
warning: the trait `anymap::any::CloneToAny` cannot be made into an object
  |
  = note: `#[warn(where_clauses_object_safety)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #51443 <https://github.com/rust-lang/rust/issues/51443>
  = note: method `clone_to_any_send` references the `Self` type in where clauses

warning: the trait `anymap::any::CloneToAny` cannot be made into an object
  |                                                                                                                  
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!                                                                                                       
  = note: for more information, see issue #51443 <https://github.com/rust-lang/rust/issues/51443>                    
  = note: method `clone_to_any_sync` references the `Self` type in where clauses                                     
                                                                                                                     
warning: the trait `anymap::any::CloneToAny` cannot be made into an object
  |                                                                                                                  
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!                                                                                                       
  = note: for more information, see issue #51443 <https://github.com/rust-lang/rust/issues/51443>                    
  = note: method `clone_to_any_send_sync` references the `Self` type in where clauses
```

We should probably clean these warnings according to https://github.com/rust-lang/rust/issues/51443 and not wait if mentioned rules will be changed in our favor.

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #251, along with some clippy lint fixes.
Also, crates.io doesn't display CI badges anymore, so dropped it from our `Cargo.toml`.

### CODE REVIEW

File: src/error.rs [hunk 1]
```diff
@@ -1,9 +1,6 @@
 //! Error types
 
 use crate::Config;
-use crossbeam_channel;
-#[cfg(target_os = "linux")]
-use mio_extras;
```
Comment (0xpr03) [inline src/error.rs:6]: Was that unused ?

Comment (JohnTitor) [reply src/error.rs:6]: Single path importing is unnecessary in the 2018 edition.
