### PR TITLE
Fix ordering of debounced events

### LINKED ISSUE #636: Panics with Rust 1.81.0
Starting with Rust 1.81.0 we see the following issues in `trunk`:

```
thread 'notify-rs debouncer loop' panicked at library/core/src/slice/sort/shared/smallsort.rs:862:5:
user-provided comparison function does not correctly implement a total order
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::slice::sort::shared::smallsort::panic_on_ord_violation
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/shared/smallsort.rs:862:5
   3: core::slice::sort::shared::smallsort::bidirectional_merge
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/shared/smallsort.rs:841:13
   4: core::slice::sort::shared::smallsort::small_sort_general_with_scratch
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/shared/smallsort.rs:289:9
   5: <T as core::slice::sort::shared::smallsort::StableSmallSortTypeImpl>::small_sort
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/shared/smallsort.rs:64:9
   6: core::slice::sort::stable::quicksort::quicksort
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/stable/quicksort.rs:27:13
   7: core::slice::sort::stable::drift::create_run
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/stable/drift.rs:257:9
   8: core::slice::sort::stable::drift::sort
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/stable/drift.rs:66:17
   9: core::slice::sort::stable::driftsort_main
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/stable/mod.rs:86:5
  10: core::slice::sort::stable::sort
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/sort/stable/mod.rs:47:5
  11: alloc::slice::stable_sort
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/slice.rs:883:5
  12: alloc::slice::<impl [T]>::sort_by
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/slice.rs:289:9
  13: notify_debouncer_full::DebounceDataInner<T>::debounced_events
             at /home/jreimann/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notify-debouncer-full-0.3.1/src/lib.rs:253:9
  14: notify_debouncer_full::new_debouncer_opt::{{closure}}
             at /home/jreimann/.cargo/registry/src/index.crates.io-6f17d22bba15001f/notify-debouncer-full-0.3.1/src/lib.rs:603:29
```

So my understanding, that's an issue with the comparator provided:

```rust
        // order events for different files chronologically, but keep the order of events for the same file
        events_expired.sort_by(|event_a, event_b| {
            // use the last path because rename events are emitted for the target path
            if event_a.paths.last() == event_b.paths.last() {
                std::cmp::Ordering::Equal
            } else {
                event_a.time.cmp(&event_b.time)
            }
        });
```

### PR DESCRIPTION
**Pull request by dfaust**
I wasn't able to reproduce the panic, but the new sort logic should fix the issue and it's also stable now.

We should release this fix as soon as possible.

Fixes #636.

### CODE REVIEW

**Comment by maratik123** [comment]
LGTM

File: notify-debouncer-full/src/lib.rs [hunk 1]
```diff
@@ -713,6 +703,39 @@ pub fn new_debouncer<F: DebounceEventHandler>(
...
+                .push_back(event);
+            acc
+        });
+
+    // push events for different paths in chronological order and keep the order of events with the same path
+    while !events_by_path.is_empty() {
+        let min_time = events_by_path
+            .values()
+            .map(|events| events[0].time)
+            .min()
```
Comment (maratik123) [inline notify-debouncer-full/src/lib.rs:723]: Seem with that total algorithmic complexity has O(n^2). May be it is need to use binary heap or something like this to track min_time?

**Review by mo8it — APPROVED** [review]

File: notify-debouncer-full/src/lib.rs (hunk 1 above)
Comment (dfaust) [reply notify-debouncer-full/src/lib.rs]: Using `BinaryHeap` improves performance a bit. Especially in scenarios with many files.

I didn't commit the benchmark because I don't know if it's useful enough. But here are the results. Unfortunately they are a bit over the place, so I'm not sure how reliable they are:

```
sort-events/sort_events with 10 files and 100k events each
    new:   [328.05 ms 330.98 ms 334.31 ms]
    old:   [408.45 ms 453.59 ms 512.18 ms] +37.042%

sort-events/sort_events with 1k files and 1k events each
    new:   [398.06 ms 401.66 ms 405.87 ms]
    old:   [448.35 ms 454.64 ms 462.24 ms] +13.190%

sort-events/sort_events with 100k files and 10 events each
    new:   [841.49 ms 906.83 ms 1.0303 s]
    old:   aborted after 10 minutes
```
